#ifndef CLINTEXPLORER_DEFINITIONS_HPP
#define CLINTEXPLORER_DEFINITIONS_HPP

#define APPLICATION_NAME "Clint Explorer"

#define DEFAULT_ZEQ_SESSION "hbp://"
#define DEFAULT_SOCKET_PORT 31400
#define DEFAULT_CLINT_HOST "http://localhost"
#define DEFAULT_CLINT_PORT 3652
#define MIN_PORT_ALLOWED 1024
#define MAX_PORT_ALLOWED 65535

#define SOCKET_MESSAGE_FILE "file\n"
#define SOCKET_MESSAGE_NOFILE "nofile\n"
#define SOCKET_MESSAGE_FILE_READED "filereaded\n"
#define SOCKET_MESSAGE_EXIT "exit\n"

#endif
